<?xml version="1.0" encoding="utf-8"?><Database Name="InteractiveHRTask" Class="InteractiveHRDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=tcp:hassanazuresqlserver.database.windows.net,1433;Initial Catalog=InteractiveHRTask;Persist Security Info=False;User ID=hassan.ali.siddig@gmail.com@hassanazuresqlserver;MultipleActiveResultSets=False;Connect Timeout=30;Encrypt=True;TrustServerCertificate=False" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="InteractiveHRTaskConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Departments" Member="Departments">
    <Type Name="Department">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Department_Employee" Member="Employees" ThisKey="Id" OtherKey="DepartmentId" Type="Employee" />
    </Type>
  </Table>
  <Table Name="dbo.Employees" Member="Employees">
    <Type Name="Employee">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FullName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Phone" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DepartmentId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Salary" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="JobTitle" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ProfilePicture" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="Employee_Vacation" Member="Vacations" ThisKey="Id" OtherKey="EmployeeId" Type="Vacation" />
      <Association Name="Department_Employee" Member="Department" ThisKey="DepartmentId" OtherKey="Id" Type="Department" IsForeignKey="true" DeleteRule="SET NULL" />
    </Type>
  </Table>
  <Table Name="dbo.Vacations" Member="Vacations">
    <Type Name="Vacation">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="EmployeeId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="StartDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="EndDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="VacationTypeId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Reason" Type="System.String" DbType="NVarChar(1000) NOT NULL" CanBeNull="false" />
      <Column Name="IsPaid" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="StatusId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Employee_Vacation" Member="Employee" ThisKey="EmployeeId" OtherKey="Id" Type="Employee" IsForeignKey="true" />
      <Association Name="VacationStatus_Vacation" Member="VacationStatus" ThisKey="StatusId" OtherKey="Id" Type="VacationStatus" IsForeignKey="true" />
      <Association Name="VacationType_Vacation" Member="VacationType" ThisKey="VacationTypeId" OtherKey="Id" Type="VacationType" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.VacationStatus" Member="VacationStatus">
    <Type Name="VacationStatus">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="VacationStatus_Vacation" Member="Vacations" ThisKey="Id" OtherKey="StatusId" Type="Vacation" />
    </Type>
  </Table>
  <Table Name="dbo.VacationTypes" Member="VacationTypes">
    <Type Name="VacationType">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="IstPaidByDefault" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="MaximumNumberOfDays" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="VacationType_Vacation" Member="Vacations" ThisKey="Id" OtherKey="VacationTypeId" Type="Vacation" />
    </Type>
  </Table>
</Database>